# Compiler using debug symbols.
CC = g++ -g
# Output filename!
out = assignment4
# Define the files to compile.
Files = Assignment4.cpp CommunicationNetwork.cpp CommunicationNetwork.h

all:
	$(CC) -o $(out) $(Files) 

clean:
	rm -f $(out)
