# Compiler using debug symbols.
CC = g++ -g -std=c++11
# Output filename!
out = Assignment12
# Define the files to compile.
Files = Assignment12.cpp HashTable.cpp HashTable.h

all:
	$(CC) -o $(out) $(Files) 

clean:
	rm -f $(out)

