# Compiler using debug symbols.
CC = g++ -g
# Output filename!
out = assignment5
# Define the files to compile.
Files = Assignment5.cpp Queue.cpp Queue.h

all:
	$(CC) -o $(out) $(Files) 

clean:
	rm -f $(out)
