# Compiler using debug symbols.
CC = g++ -g
# Output filename!
out = assignment6
# Define the files to compile.
Files = Assignment6.cpp MovieTree.cpp MovieTree.h

all:
	$(CC) -o $(out) $(Files) 

clean:
	rm -f $(out)
