# Compiler using debug symbols.
CC = g++ -g
# Output filename!
out = Assignment11
# Define the files to compile.
Files = Assignment11.cpp Graph.cpp Graph.h

all:
	$(CC) -o $(out) $(Files) 

clean:
	rm -f $(out)

zip:
	zip Assignment11.zip $(files)
