# Compiler using debug symbols.
CC = g++ -g
# Output filename!
out = assignment10
# Define the files to compile.
Files = Assignment10.cpp Graph.cpp Graph.h

all:
	$(CC) -o $(out) $(Files) 

clean:
	rm -f $(out)
